# Example Configuration File (config.yml)

# Server Configuration
server:
  port: 8080
  host: localhost
  timeout: 3000

# Database Configuration
database:
  type: MySQL
  host: db.example.com
  port: 3306
  username: user
  password: password123
  dbname: mydatabase

# Logging Configuration
logging:
  level: INFO
  format: text
  file: /var/log/myapp.log

# Feature Flags
features:
  feature1: true
  feature2: false

# External API Configuration
external_api:
  endpoint: https://api.example.com
  key: myapikey123
