name: Bug report
description: Report a bug to help us improve
title: "[BUG] - "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide the details below.

  - type: input
    id: title
    attributes:
      label: Short Summary
      description: A short summary of the bug.
      placeholder: Provide a concise description of the issue
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug in detail
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      placeholder: List the steps to reproduce the bug
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Provide links or attach screenshots

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Provide details about the environment where the bug occurred.
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
      multiple: true
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Specify the operating system version (e.g., Windows 10, macOS Catalina)
      placeholder: Provide the OS version
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Specify the browser used (e.g., Chrome, Safari)
      placeholder: Provide the browser name and version
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add any additional information that might be relevant

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs or error messages here.
      placeholder: Provide logs or error messages

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have a potential solution, let us know here.
      placeholder: Suggest a solution or workaround
